// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASymP3lPZmXpiHB37iEJVGpGNNAPm18VM',
    appId: '1:901710136299:web:1c76e3a025d58be8ee4fae',
    messagingSenderId: '901710136299',
    projectId: 'streaming-app-47918',
    authDomain: 'streaming-app-47918.firebaseapp.com',
    storageBucket: 'streaming-app-47918.appspot.com',
    measurementId: 'G-02SSTRV2ZZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7eQea8OhyexP_3CzVzZfQrej1QJ5ujeA',
    appId: '1:901710136299:android:30c0277131c961d4ee4fae',
    messagingSenderId: '901710136299',
    projectId: 'streaming-app-47918',
    storageBucket: 'streaming-app-47918.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGLWn1T8Nw2o8aE66BGUtC8tctZqQRAoY',
    appId: '1:901710136299:ios:241dfdf48150f316ee4fae',
    messagingSenderId: '901710136299',
    projectId: 'streaming-app-47918',
    storageBucket: 'streaming-app-47918.appspot.com',
    iosClientId: '901710136299-nclccg1sfv9hk9o2j5gm1rlqgsdg7r77.apps.googleusercontent.com',
    iosBundleId: 'com.example.streamingApp',
  );
}
